---
# tasks file for docker
- name: Purge old docker packages
  apt:
    name: "{{item}}"
    state: absent
    autoremove: yes
  with_items:
    - lxc-docker
    - docker-engine
    - docker.io

- name: Remove existing Docker Repositories
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ansible_distribution | lower}}-{{ansible_distribution_release}} {{item}}
    state: absent
  with_items:
#    - testing
    - experimental

- name: Install https support packages for apt
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Add docker GPG Keys to apt 
  apt_key: 
    keyserver: hkp://{{item}}:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
    state: present
  with_items:
    # - ha.pool.sks-keyservers.net
    - pgp.mit.edu
    - keyserver.ubuntu.com

- name: Add Docker Repository
  apt_repository: 
    repo: deb https://apt.dockerproject.org/repo {{ansible_distribution | lower }}-{{ansible_distribution_release}} {{docker_build}}
    state: present
    update_cache: yes 

- name: Install {{docker_build}} Docker Engine
  apt:
    name: docker-engine
    state: present
